const RightSideIconApi = [
  {
    id: 1,
    title: "জনতার কথা",
    image: "assets/images/rightSideIcon/1.png",
    link: "#",
    background: `#00CBFF`,
  },
  {
    id: 2,
    title: "চলুন করি",
    image: "assets/images/rightSideIcon/2.png",
    link: "#",
    background: "#8CE900",
  },
  {
    id: 3,
    title: "চলুন করি",
    image: "assets/images/rightSideIcon/3.png",
    link: "#",
    background: "#A21594",
  },
  {
    id: 4,
    title: "চলুন করি",
    image: "assets/images/rightSideIcon/4.png",
    link: "#",
    background: "#01C19A",
  },
  {
    id: 5,
    title: "চলুন করি",
    image: "/assets/images/rightSideIcon/5.png",
    link: "#",
    background: "#42AD2B",
  },
  {
    id: 6,
    title: "চলুন করি",
    image: "/assets/images/rightSideIcon/6.png",
    link: "#",
    background: "#A21594",
  },
  {
    id: 7,
    title: "চলুন করি",
    image: "/assets/images/rightSideIcon/7.png",
    link: "#",
    background: "#8CE900",
  },
  {
    id: 8,
    title: "চলুন করি",
    image: "/assets/images/rightSideIcon/8.png",
    link: "#",
    background: "#A21594",
  },
  {
    id: 9,
    title: "চলুন করি",
    image: "/assets/images/rightSideIcon/9.png",
    link: "#",
    background: "#01C19A",
  },
];
export default RightSideIconApi;
