const SelectedMenuCardApi = [
  {
    id: 1,
    montronaloy: "ডাক ও টেলিযোগাযোগ বিভাগ",
    karjokrom: "চলুন করি",
    sheti: "সমাপ্ত",
    start: "3/4/2020",
    end: "4/6/2020",
    image: "https://dummyimage.com/300x240/#fff/#eee",
    title: "Amer sonar  করোনা ভাইরাস সচেতনতা স্লোগান তৈরি করুন",
    date: "০৩ অক্টোবর ২০২০",
    subtitle: "জনতার সরকার পোর্টালে একটি স্লোগান লিখুন",
  },
  {
    id: 2,
    montronaloy: "সাস্থ্য সেবা বিভাগ",
    karjokrom: "চলুন করি",
    sheti: "সমাপ্ত",
    start: "3/4/2020",
    end: "4/6/2020",
    image: "https://dummyimage.com/300x240/#fff/#eee",
    title: "স্লোগান প্রতিযোগিতা: করোনা ভাইরাস সচেতনতা স্লোগান তৈরি করুন",
    date: "০৩ অক্টোবর ২০২০",
    subtitle: "জনতার সরকার পোর্টালে একটি স্লোগান লিখুন",
  },
  {
    id: 3,
    montronaloy: "ডাক ও টেলিযোগাযোগ বিভাগ",
    karjokrom: "জনতার কথা",
    sheti: "সমাপ্ত",
    start: "3/4/2020",
    end: "4/6/2020",
    image: "https://dummyimage.com/300x240/#fff/#eee",
    title: "স্লোগান প্রতিযোগিতা: করোনা ভাইরাস সচেতনতা স্লোগান তৈরি করুন",
    date: "০৩ অক্টোবর ২০২০",
    subtitle: "জনতার সরকার পোর্টালে একটি স্লোগান লিখুন",
  },
  {
    id: 4,
    montronaloy: "স্থানীয় সরকার বিভাগ",
    karjokrom: "মত প্রকাশ",
    sheti: "সমাপ্ত",
    start: "3/4/2020",
    end: "4/6/2020",
    image: "https://dummyimage.com/300x240/#fff/#eee",
    title: "স্লোগান প্রতিযোগিতা: করোনা ভাইরাস সচেতনতা স্লোগান তৈরি করুন",
    date: "০৩ অক্টোবর ২০২০",
    subtitle: "জনতার সরকার পোর্টালে একটি স্লোগান লিখুন",
  },
  {
    id: 5,
    montronaloy: "স্থানীয় সরকার বিভাগ",
    karjokrom: "মত প্রকাশ",
    sheti: "সমাপ্ত",
    start: "3/4/2020",
    end: "4/6/2020",
    image: "https://dummyimage.com/300x240/#fff/#eee",
    title: "স্লোগান প্রতিযোগিতা: করোনা ভাইরাস সচেতনতা স্লোগান তৈরি করুন",
    date: "০৩ অক্টোবর ২০২০",
    subtitle: "জনতার সরকার পোর্টালে একটি স্লোগান লিখুন",
  },
  {
    id: 6,
    montronaloy: "স্থানীয় সরকার বিভাগ",
    karjokrom: "সৃজনশীল কণার",
    sheti: "সমাপ্ত",
    start: "3/4/2020",
    end: "4/6/2020",
    image: "https://dummyimage.com/300x240/#fff/#eee",
    title: "স্লোগান প্রতিযোগিতা: করোনা ভাইরাস সচেতনতা স্লোগান তৈরি করুন",
    date: "০৩ অক্টোবর ২০২০",
    subtitle: "জনতার সরকার পোর্টালে একটি স্লোগান লিখুন",
  },
  {
    id: 7,
    montronaloy: "স্থানীয় সরকার বিভাগ",
    karjokrom: "আমাদের ব্লগ",
    sheti: "সমাপ্ত",
    start: "3/4/2020",
    end: "4/6/2020",
    image: "https://dummyimage.com/300x240/#fff/#eee",
    title: "স্লোগান প্রতিযোগিতা: করোনা ভাইরাস সচেতনতা স্লোগান তৈরি করুন",
    date: "০৩ অক্টোবর ২০২০",
    subtitle: "জনতার সরকার পোর্টালে একটি স্লোগান লিখুন",
  },
];
export default SelectedMenuCardApi;
